spring:
  application:
    name: sab-agent
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model:  llama3.2
        options:
          temperature: 0.7
      embedding:
        model: nomic-embed-text
      vectorstore:
        pgvector:
          intialize-schema: true
          dimensions: 1536
    mcp:
      client:
        name: dvaas-mcp-client
        version: 0.0.1
        toolcallback:
          enabled: true
        stdio:
          connections:
            docker-shopping-server:
              command: "docker"
              args:
                - "run"
                - "-i" # Essential for terminal pipelining stream channels
                - "--rm"
                - "tiger123/sab-mcp-server:main"

SERVER:
  PORT: 8081