spring:
  application:
    name: dvaas-client
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model:  llama3.2
        options:
          temperature: 0.7
      embedding:
        model: nomic-embed-text
      vectorstore:
        pgvector:
          intialize-schema: true
          dimensions: 1536
    mcp:
      client:
        name: dvaas-mcp-client
        version: 0.0.1
        toolcallback:
          enabled: true
        stdio: # Use stdio transport layers for local execution pipelines
          connections:
            local-weather-server:
              command: "java"
              args:
                - "-jar"
                - "C:\\Users\\Sunil\\git\\mcp-server\\mcp-server\\target\\mcp-server-0.0.1-SNAPSHOT.jar"

SERVER:
  PORT: 8081